# Initial Cleaning

This section handles cleaning the raw data from the review and metadata files and joining them together.
I then export this and comment everything out and use the newly exported dataset as the original source of truth.

### Importing

In [ ]:
# import pandas as pd
# import gzip
# import json

# def parse(path):
#   g = gzip.open(path, 'rb')
#   for l in g:
#     yield json.loads(l)

# def getDF(path):
#   i = 0
#   df = {}
#   for d in parse(path):
#     df[i] = d
#     i += 1
#     if i > 50000:
#       break
#   return pd.DataFrame.from_dict(df, orient='index')

# df_reviews = getDF('data/Books_5.json.gz')
# df_metadata = getDF('data/meta_Books.json.gz')

### Renaming

In [ ]:
# review_column_rename_map = {
#     "overall": "user_rating",
#     "verified": "user_verified_purchase",
#     "reviewTime": "user_review_date_raw",
#     "reviewerID": "user_id",
#     "asin": "book_id",
#     "style": "book_format",
#     "reviewerName": "user_name",
#     "reviewText": "user_review_text",
#     "summary": "user_review_summary",
#     "unixReviewTime": "user_review_timestamp",
#     "vote": "user_review_helpful_votes",
# }

# metadata_column_rename_map = {
#     "category": "book_category",
#     "description": "book_description",
#     "title": "book_title",
#     "brand": "book_brand",
#     "rank": "book_rank",
#     "price": "book_price",
#     "asin": "book_id",
#     "imageURL": "book_image_url",
# }

# df_reviews = df_reviews.rename(columns=review_column_rename_map)
# df_metadata = df_metadata.rename(columns=metadata_column_rename_map)

### Dropping rows and columns

In [ ]:

# review_columns_to_drop = [
#     # "user_review_helpful_votes",
#     "user_review_date_raw",
#     "user_verified_purchase",
#     "user_name",
#     "user_review_helpful_votes",
#     "image"
# ]
# df_reviews.drop(columns=review_columns_to_drop, inplace=True)

# metadata_columns_to_drop = [
#     "tech1", 
#     "fit", 
#     "tech2", 
#     "feature",  
#     "also_buy", 
#     "main_cat", 
#     "similar_item", 
#     "date",
#     'imageURLHighRes',
#     'also_view'
# ]
# df_metadata.drop(columns=metadata_columns_to_drop, inplace=True)

In [ ]:
# df_reviews.head(5)

,user_rating,user_id,book_id,book_format,user_review_text,user_review_summary,user_review_timestamp
0,5.0,A1REUF3A1YCPHM,0001713353,{'Format:': ' Hardcover'},"The King, the Mice and the Cheese by Nancy Gur...",A story children will love and learn from,1112140800
1,5.0,AVP0HXC9FG790,0001713353,NaN,The kids loved it!,Five Stars,1466380800
2,5.0,A324TTUBKTN73A,0001713353,{'Format:': ' Paperback'},My students (3 & 4 year olds) loved this book!...,Five Stars,1453593600
3,5.0,A2RE7WG349NV5D,0001713353,{'Format:': ' Paperback'},LOVE IT,Five Stars,1436400000
4,5.0,A32B7QIUDQCD0E,0001713353,NaN,Great!,Five Stars,1421539200

### Cleaning

In [ ]:
# from datetime import datetime
# import re


# def clean_book_format(text):
#     """
#         Input: {'Format:': ' Paperback'} 
#         Output: 'paperback'
#     """
#     if isinstance(text, dict):
#         value = str(list(text.values())[0]).strip().lower()
#         return value
#     return None

# def convert_unix_timestamp_to_year(timestamp):
#     """
#         Input: 1112140800 (March 30 2005)
#         Output: 2005
#     """
#     year = datetime.fromtimestamp(timestamp).year
#     return year

# def parse_rank_from(book_rank):
#     """
#         Input: '1,349,781 in Books ('
#         Output: 1349781
#     """
#     match = re.search(r'[\d,]+', book_rank)
#     if not match:
#         return None  
#     return int(match.group().replace(',', ''))

# def remove_dollar_sign(text):
#     return text.strip("$")

# df_reviews["book_format"] = df_reviews["book_format"].apply(clean_book_format)
# df_reviews["user_review_timestamp"] = df_reviews["user_review_timestamp"].apply(convert_unix_timestamp_to_year)
# df_metadata["book_price"] = df_metadata["book_price"].apply(remove_dollar_sign)
# df_metadata["book_rank"] = df_metadata["book_rank"].apply(parse_rank_from)

In [ ]:
# df = df_reviews.merge(df_metadata, on="book_id")
# df.dropna(axis=0, inplace=True)

# df.to_csv("./data/dataset.csv", index=False)

### Text Embeddings

In [50]:
import pandas as pd

df = pd.read_csv("./data/dataset.csv")
df.head()

,user_rating,user_id,book_id,book_format,user_review_text,user_review_summary,user_review_timestamp,book_category,book_description,book_title,book_brand,book_rank,book_price,book_image_url
0,5.0,A1REUF3A1YCPHM,0001713353,hardcover,"The King, the Mice and the Cheese by Nancy Gur...",A story children will love and learn from,2005,"['Books', ""Children's Books"", 'Literature & Fi...","[""THE KING, THE MICE AND THE CHEESE follows a ...","King, the Mice and the Cheese (Beginner Books)",Visit Amazon's Nancy Gurney Page,1461315,12.33,[]
1,5.0,A324TTUBKTN73A,0001713353,paperback,My students (3 & 4 year olds) loved this book!...,Five Stars,2016,"['Books', ""Children's Books"", 'Literature & Fi...","[""THE KING, THE MICE AND THE CHEESE follows a ...","King, the Mice and the Cheese (Beginner Books)",Visit Amazon's Nancy Gurney Page,1461315,12.33,[]
2,5.0,A2RE7WG349NV5D,0001713353,paperback,LOVE IT,Five Stars,2015,"['Books', ""Children's Books"", 'Literature & Fi...","[""THE KING, THE MICE AND THE CHEESE follows a ...","King, the Mice and the Cheese (Beginner Books)",Visit Amazon's Nancy Gurney Page,1461315,12.33,[]
3,5.0,A3H9YD6K9TVKDP,0001713353,hardcover,Over and over the king has problems. Fortunat...,Not Nice Mice,2013,"['Books', ""Children's Books"", 'Literature & Fi...","[""THE KING, THE MICE AND THE CHEESE follows a ...","King, the Mice and the Cheese (Beginner Books)",Visit Amazon's Nancy Gurney Page,1461315,12.33,[]
4,5.0,A3M314LI9OYME,0001713353,hardcover,I remember reading my parents' copy of this bo...,One of my favorite kids' stories,2013,"['Books', ""Children's Books"", 'Literature & Fi...","[""THE KING, THE MICE AND THE CHEESE follows a ...","King, the Mice and the Cheese (Beginner Books)",Visit Amazon's Nancy Gurney Page,1461315,12.33,[]